### ISSUE TITLE
Workflow fails because `action-docker-layer-caching` fails with `GitHub Actions services are currently unavailable`

### ISSUE THREAD

**Issue by bsemp** [satackey/action-docker-layer-caching#11]
**Describe the bug**

I am using this the action as described in the documentation for caching docker layer to speed up docker build of multiple docker images of NodeJS applications.
However from time to time but more often these days, I see errors on either layer downloading step or post step about `GitHub Actions services are currently unavailable` that make the workflow to fail.

**To Reproduce**

Run the workflow with the action satackey/action-docker-layer-caching@v0.0.4

My workflow is as follow:

```
on:
  push:
    branches:
      - master
    paths:
      - packages/**
name: Kubernetes Application
jobs:
  docker-build:
    name: Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [myimage1, myimage2, myimage3, myimage4, myimage5]
    steps:
      - uses: actions/checkout@v2
      - name: Env Setup
        run: |
          echo ::set-env name=GIT_TAG::$(echo "`cat packages/${{ matrix.module }}/package.json | jq -r '.version'`-${GITHUB_SHA::8}")
      - name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.4
        with:
          key: ${{ matrix.module }}-docker-cache-{hash}
          restore-keys: |
            ${{ matrix.module }}-docker-cache-
      - uses: docker/build-push-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ matrix.module }}
          dockerfile: packages/${{ matrix.module }}/Dockerfile
          build_args: VERSION=${{ env.GIT_TAG }}
          add_git_labels: true
          tag_with_ref: true
          tags: ${{ env.GIT_TAG }}
```

**Expected behavior**

Workflow does not fail even if some layers cannot be downloaded or saved to the cache.

**Debug logs**

Error seen in downloading step

```
Error: getCacheEntry failed: GitHub Actions services are currently unavailable. Try again later. Activity Id: 6b09e32f-887a-4e27-98c5-c6060c2c1c26
    at /home/runner/work/_actions/satackey/action-docker-layer-caching/v0.0.4/dist/ttsc-dist/main.js/index.js:45495:15
    at Generator.throw (<anonymous>)
    at rejected (/home/runner/work/_actions/satackey/action-docker-layer-caching/v0.0.4/dist/ttsc-dist/main.js/index.js:45426:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
##[error]Error: getCacheEntry failed: GitHub Actions services are currently unavailable. Try again later. Activity Id: 6b09e32f-887a-4e27-98c5-c6060c2c1c26
```

Errors seen in post step:

```
Start storing layer cache: layer-myimage1-docker-cache-9fed80be61e73bca64cb95f027a1da7d2c5d68ed5932436465b16fb13d36ceea
##[error]Unexpected error: Error: reserveCache failed: GitHub Actions services are currently unavailable. Try again later. Activity Id: 6b095012-887a-4e27-98c5-c6060c2c1c26
Error: reserveCache failed: GitHub Actions services are currently unavailable. Try again later. Activity Id: 6b095012-887a-4e27-98c5-c6060c2c1c26
    at /home/runner/work/_actions/satackey/action-docker-layer-caching/v0.0.4/dist/ttsc-dist/post.js/index.js:45520:15
    at Generator.throw (<anonymous>)
    at rejected (/home/runner/work/_actions/satackey/action-docker-layer-caching/v0.0.4/dist/ttsc-dist/post.js/index.js:45451:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
##[error]Error: reserveCache failed: GitHub Actions services are currently unavailable. Try again later. Activity Id: 6b095012-887a-4e27-98c5-c6060c2c1c26
##[error]Unexpected error: Error: reserveCache failed: GitHub Actions services are currently unavailable. Try again later. Activity Id: 6b095010-887a-4e27-98c5-c6060c2c1c26
##[error]Unexpected error: Error: reserveCache failed: GitHub Actions services are currently unavailable. Try again later. Activity Id: 49140aa7-150c-41fb-b468-c22336268aab
```
**Runner Environment (please complete the following information):**
 - OS: ubuntu-latest
 - Action version: v0.0.4

**Additional context**

**Comment by satackey** [comment]
You can set `continue-on-error` to `true` to mark success even if the step fails.

```yaml
      - name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.4
        continue-on-error: true
        with:
          key: ${{ matrix.module }}-docker-cache-{hash}
          restore-keys: |
            ${{ matrix.module }}-docker-cache-
```

**Comment by bsemp** [comment]
does `continue-on-error: true` will work for the post step ?

**Comment by satackey** [comment]
Yes. 

I tested it by adding comma to key to make step failure.

- [Workflow file](https://github.com/satackey/github-actions-test/actions/runs/187200332/workflow)
- [Job result](https://github.com/satackey/github-actions-test/runs/923463648)
  <img width="1382" alt="image" src="https://user-images.githubusercontent.com/21271711/88816891-da6e2400-d1f7-11ea-8bd1-718f82d9902c.png">

**Comment by bsemp** [comment]
Perfect, thank you very much for your help
