### ISSUE TITLE
Fails with docker images pulled by sha

### ISSUE THREAD

**Issue by kshpytsya** [satackey/action-docker-layer-caching#17]
Docker provides a way for referring to images by their SHA hash instead of tags, like this:

```sh
$ docker pull pierrezemb/gostatic@sha256:e28d48e17840c5104b5133c30851ac45903b1d2f268d108c4cd0884802c9c87e
$ docker images|grep gostatic
pierrezemb/gostatic                                                              <none>                         4569615e9ed0        2 weeks ago
      7.72MB
```

Notice the "<none>" part.

Now, apparently this causes the docker layer caching action to do the equivalent of following under the hood:

```sh
$ docker history -q 'pierrezemb/gostatic:<none>'
Error response from daemon: invalid reference format
```

In the logs of Github build I see:

```
docker history -q pierrezemb/gostatic:<none>










Error: The process '/usr/bin/docker' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/satackey/action-docker-layer-caching/v0.0.5/dist/ttsc-dist/post.js/index.js:1300:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/satackey/action-docker-layer-caching/v0.0.5/dist/ttsc-dist/post.js/index.js:1283:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/satackey/action-docker-layer-caching/v0.0.5/dist/ttsc-dist/post.js/index.js:1183:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
##[error]Error: The process '/usr/bin/docker' failed with exit code 1
```

**Comment by satackey** [comment]
I hadn't considered pulling by digest, I'll fix it soon.

**Comment by peterbe** [comment]
I'm getting the same error here:
```
Post job cleanup.
Error: The process '/usr/bin/docker' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/satackey/action-docker-layer-caching/v0.0.8/dist/ttsc-dist/post.js/index.js:1300:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/satackey/action-docker-layer-caching/v0.0.8/dist/ttsc-dist/post.js/index.js:1283:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/satackey/action-docker-layer-caching/v0.0.8/dist/ttsc-dist/post.js/index.js:1183:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
##[error]Error: The process '/usr/bin/docker' failed with exit code 1
```
https://github.com/mdn/kuma/runs/1063849218

My config can be seen here https://github.com/mdn/kuma/pull/7456/files#diff-12a86cef0c4707531fdbabac3e38cb2aR27 if that helps. 
Is it because I'm not specifying a key?

**Comment by raphaelvigee** [comment]
I'm encountering the same issue, any splution for it ?

**Comment by rcowsill** [comment]
> I'm getting the same error here: [...]
> Is it because I'm not specifying a key?

That looks like the same issue as the OP; the [kuma_base Dockerfile](https://github.com/mdn/kuma/blob/master/docker/images/kuma_base/Dockerfile#L1) specifies a source image by digest. That image isn't dangling so the action expects it to have a valid tag instead of `<none>`.

> I'm encountering the same issue, any solution for it ?

Until this issue is resolved I think the only workaround is to specify images by tag instead of by digest.

**Comment by ruohola** [comment]
One thing to also consider is to keep support for specifying the tag AND the hash. This form is common **even though the tag here does absolutely nothing, but only helps the reader:**

```
FROM python:3.9.4-slim-buster@sha256:de9482638c1354f5178efc90431de2a42e863a12bf3df41d7fa30d5c10fe543d
```


> One useful trick know is that you don’t have to remove the tag if you want to add a digest. If both are present then the tag is ignored, so you can leave it in for human readability
>
>https://www.whitesourcesoftware.com/free-developer-tools/blog/overcoming-dockers-mutable-image-tags/

**Comment by rcowsill** [comment]
> One thing to also consider is to keep support for specifying the tag AND the hash.

I've just confirmed that docker does treat that form exactly the same as only specifying the hash. That means that it'll just work when the action supports images specified by hash.

**Comment by ruohola** [comment]
> > One thing to also consider is to keep support for specifying the tag AND the hash.
> 
> 
> 
> I've just confirmed that docker does treat that form exactly the same as only specifying the hash. That means that it'll just work when the action supports images specified by hash.
> 
> 
> 
> 

Yes, to Docker:

```
FROM python:3.9.4-slim-buster@sha256:de9482638c1354f5178efc90431de2a42e863a12bf3df41d7fa30d5c10fe543d
```
and

```
FROM python@sha256:de9482638c1354f5178efc90431de2a42e863a12bf3df41d7fa30d5c10fe543d
```

are identical. Just wasn't familiar with this Action's internals and wanted to give a heads up about it :)

**Comment by ruohola** [comment]
I still get this every time **even with unpinned images**:

```
2021-04-17T11:26:40.7196841Z ##[group]Run satackey/action-docker-layer-caching@v0.0.11
2021-04-17T11:26:40.7197576Z with:
2021-04-17T11:26:40.7198177Z   key: docker-layer-caching-CI-{hash}
2021-04-17T11:26:40.7200184Z   restore-keys: docker-layer-caching-CI-
2021-04-17T11:26:40.7200885Z   concurrency: 4
2021-04-17T11:26:40.7201355Z   skip-save: false
2021-04-17T11:26:40.7201826Z ##[endgroup]
2021-04-17T11:26:41.1220958Z Root cache could not be found. aborting.
```

**Comment by ruohola** [comment]
> I still get this every time even after switching to images pinned by tag and not sha:
> 
> ```
> 2021-04-17T11:26:40.7196841Z ##[group]Run satackey/action-docker-layer-caching@v0.0.11
> 2021-04-17T11:26:40.7197576Z with:
> 2021-04-17T11:26:40.7198177Z   key: docker-layer-caching-CI-{hash}
> 2021-04-17T11:26:40.7200184Z   restore-keys: docker-layer-caching-CI-
> 2021-04-17T11:26:40.7200885Z   concurrency: 4
> 2021-04-17T11:26:40.7201355Z   skip-save: false
> 2021-04-17T11:26:40.7201826Z ##[endgroup]
> 2021-04-17T11:26:41.1220958Z Root cache could not be found. aborting.
> ```

Actually this only happens when building with docker-compose.

**Comment by ghost** [comment]
Any updates on this?
I am getting the same `Error: The process '/usr/bin/docker' failed with exit code 1` in the Post Layer Cache step, on the first run, with the following configuration:
![code](https://user-images.githubusercontent.com/86379498/127535257-8623911f-9306-4d69-a720-25cf0eb5daae.png)
