### ISSUE TITLE
Error: The process '/usr/bin/docker' failed with exit code 1

### ISSUE THREAD

**Issue by xenoterracide** [satackey/action-docker-layer-caching#50]
on attempt to save the cache

```
Error: The process '/usr/bin/docker' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/satackey/action-docker-layer-caching/v0.0.8/dist/ttsc-dist/post.js/index.js:1300:25)
Error: Error: The process '/usr/bin/docker' failed with exit code 1
    at ExecState.CheckComplete (/home/runner/work/_actions/satackey/action-docker-layer-caching/v0.0.8/dist/ttsc-dist/post.js/index.js:1283:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/satackey/action-docker-layer-caching/v0.0.8/dist/ttsc-dist/post.js/index.js:1183:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```
```yaml
  builder-liquibase:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: satackey/action-docker-layer-caching@v0.0.8
```
the build appears to have no additional useful information.

It may be relevant that I'm using the cache across 2 jobs... but I'm not certain of that.

**Comment by xenoterracide** [comment]
derp this has already been reported... I was mislead by the beginning of the other title

**Comment by nicwortel** [comment]
@xenoterracide what issue are you referring to?

**Comment by xenoterracide** [comment]
#49
