### ISSUE TITLE
docker load` fails with "evalSymlinksInScope: too many links"

### ISSUE THREAD

**Issue by iHiD** [satackey/action-docker-layer-caching#65]
**Describe the bug**
`docker load` fails as follows:

```
/bin/sh -c tar cf - . | docker load
evalSymlinksInScope: too many links in /var/lib/docker/tmp/docker-import-485111148/fbf06cbdaebb44ef253d774ca00108ac5e04fc0eb46b5587361e0d958e3f6bce/layer.tar
Error: The process '/bin/sh' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/satackey/action-docker-layer-caching/v0.0.5/dist/ttsc-dist/main.js/index.js:1300:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/satackey/action-docker-layer-caching/v0.0.5/dist/ttsc-dist/main.js/index.js:1283:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/satackey/action-docker-layer-caching/v0.0.5/dist/ttsc-dist/main.js/index.js:1183:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
Error: Error: The process '/bin/sh' failed with exit code 1
```

**To Reproduce**
This happens on all builds in [this repo](https://github.com/exercism/v3-website/)

**Debug logs**
A sample run can be [seen here](https://github.com/exercism/v3-website/runs/1315032507#step:3:211)

The config file is [here](https://github.com/exercism/v3-website/blob/master/.github/workflows/deploy.yml#L39-L45)

**Additional context**
I am intending to cycle the cache-key next, but wanted to log this as that will probably fix the symptom not the cause.

**Comment by WengerK** [comment]
For those having the same issue, updating from `v0.0.5` to `v0.0.8` fix the issue on our projects.
Hope it would help

**Comment by iHiD** [comment]
The issue has fixed itself for us. We're also now on `0.0.8`. I'm not sure exactly when/what has fixed it, but I'll close this and suggest you follow @WengerK's advice to update.
